# Generated by Django 6.0.5 on 2026-05-24 05:34

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(unique=True)),
                ('draw_date', models.DateTimeField()),
                ('win_numbers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=6)),
                ('bonus_number', models.IntegerField()),
                ('is_drawn', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lotteryround')),
            ],
        ),
        migrations.CreateModel(
            name='LottoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numbers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=6)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='WinningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, choices=[(1, '1등'), (2, '2등'), (3, '3등'), (4, '4등'), (5, '5등')], null=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.lottoticket')),
            ],
        ),
    ]
